

add_subdirectory(smc)
add_subdirectory(generator)
add_subdirectory(readAndWrite)
target_include_directories(smc PUBLIC /home/kqweqk/smc2/smc_7_6_0/lib/C++)
add_subdirectory(regex)
include_directories(regex)
include_directories(smc)
include_directories(generator)
include_directories(readAndWrite)
include_directories(analyser)
add_subdirectory(analyser)
add_subdirectory(flex)
include_directories(flex)
add_executable(LAB1 main.cpp )
add_executable(GENERATE mainG.cpp )

target_link_libraries(LAB1 smc writer regex abstractAnalys flex)
target_link_libraries(GENERATE generator)
